spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.gumall:3306/gumall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gumall:8848
  application:
    name: gumall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: redis.gumall
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8080
logging:
  level:
    com.xyz.gumall: info
