spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.gumall:3306/gumall_wms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gumall:8848
  application:
    name: gumall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8080
logging:
  level:
    com.xyz.gumall: debug
