spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: youraccess-key
      secret-key: yoursecret-key
      oss:
        endpoint: oss-cn-hongkong.aliyuncs.com
        bucket: yourbucket

  application:
    name: gumall-third-party
server:
  port: 30000
